.goreleaser.yaml
README.md

**What**
This pull request fixes network bind plug for snapcraft and also update docs

build(ci): snapcraft network-bind and docs

---

.goreleaser.yaml
README.md

This PR will auto add release notes to release page. 
Also added couple of quick handly links in main docs

build(ci): add release note and docs update

---

backend/handlers/base/informers.go
backend/handlers/workloads/deployments/deployments.go
backend/handlers/workloads/pods/deployments.go
backend/handlers/workloads/pods/pods.go

This PR will fix pods list sse events in deployments API/Page. Previously some events were getting missed

fix: pods deployment list sse events

---

.goreleaser.yaml
backend/cmd/cmd.go
backend/cmd/version.go
backend/handlers/apply/apply.go
backend/main.go

This PR adds:
* Build commit to binary.
* Better error output.
* Startup banner - CLI

feat: trim path and add short commit to build

---

client/src/components/app/Common/AddResource/index.css
client/src/components/app/Common/AddResource/index.tsx
client/src/components/app/Common/Details/index.tsx
client/src/components/app/Common/Hooks/EventSource/index.tsx
client/src/components/app/Details/YamlEditor/index.tsx
client/src/components/app/MiscDetailsContainer/Logs/SocketLogs/index.tsx
client/src/components/app/Table/TableFacetedFilter/index.tsx
client/src/components/app/Table/TableToolbar/index.tsx
client/src/main.tsx
client/vite.config.ts

This PR does 
1) Fix the issue reported https://github.com/kubewall/kubewall/issues/10
2) Adds a new feature of Add Resource
3) Updates the local dev api port listener from 2121 to 7080

Bug fix and add resource feature

---

backend/handlers/app/config.go

This PR resolved the issue of server IP not getting saved because of a typo.
Fixed #17

fix: serverIP is not getting saved.

---

charts/kubewall/.helmignore
charts/kubewall/Chart.yaml
charts/kubewall/README.md
charts/kubewall/templates/NOTES.txt
charts/kubewall/templates/_helpers.tpl
charts/kubewall/templates/cluster-role-binding.yaml
charts/kubewall/templates/deployment.yaml
charts/kubewall/templates/pvc.yaml
charts/kubewall/templates/service.yaml
charts/kubewall/templates/serviceaccount.yaml
charts/kubewall/templates/tls-secret.yaml
charts/kubewall/values.yaml

Added helm chart and README.md for kubewall installation

Added helm chart for kubewall

---

client/src/KubeWall.tsx
client/src/app.tsx
client/src/components/app/Common/AddResource/index.tsx
client/src/components/app/Common/Details/index.tsx
client/src/components/app/Common/List/index.tsx
client/src/components/app/Details/Card/ExpandableCard/index.tsx
client/src/components/app/Details/Overview/index.tsx
client/src/components/app/KubeConfiguration/AddConfiguration/index.tsx
client/src/components/app/KubeConfiguration/index.tsx
client/src/components/app/MiscDetailsContainer/DeploymentDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/SecretDetailsContainer.tsx
client/src/components/app/Sidebar/Navigator/index.tsx
client/src/components/app/Sidebar/index.tsx
client/src/components/app/Table/TableCells/index.tsx
client/src/components/app/Table/TableCells/nameCell.tsx
client/src/components/app/Table/TableDelete/index.tsx
client/src/components/app/Table/data-table.tsx
client/src/components/app/Table/index.css
client/src/routes/index.tsx
client/src/types/misc.d.ts
client/src/utils/ListType/ListDefinations.ts
client/src/utils/MiscUtils.ts

This PR add/updates
1. New Route to have cluster as query param
2. Fix delete issue
3. Decode feature of Secrets
4. Added title to tab
5. New validation for new cluster name
6. Allow multiple sidebar accordions to be opened

feat: New route and features

---

client/src/utils/ListType/ListDefinations.ts

This PR adds in
1) Sorting capability to pods tables

Add sorting option to age column in pod list

---

backend/handlers/app/config.go
backend/handlers/apply/helper.go
backend/handlers/crds/crds/definitions.go
backend/handlers/nodes/transromer.go
backend/handlers/workloads/pods/transformer.go
client/src/components/app/Common/DeboucedInput/index.tsx
client/src/components/app/Common/Hooks/Details/detailsWrapper.tsx
client/src/components/app/Common/Hooks/Details/fetchDataForDetails.tsx
client/src/components/app/Common/List/index.tsx
client/src/components/app/Sidebar/index.tsx
client/src/components/app/Table/TableCells/index.tsx
client/src/data/CustomResources/CustomResourcesDefinitionDetailsSlice.ts
client/src/data/CustomResources/CustomResourcesSlice.ts
client/src/redux/store.ts
client/src/types/CustomResources/customResourcesDefinitionDetails.d.ts
client/src/types/CustomResources/customResourcesDefinitions.d.ts
client/src/types/CustomResources/index.ts
client/src/utils/CustomResources/CustomResourcesDefinitions.ts
client/src/utils/CustomResources/index.ts
client/src/utils/DetailType/DetailDefinations.ts
client/src/utils/ListType/ListDefinations.ts
client/src/utils/Workloads/PodUtils.ts
client/src/utils/index.ts

This PR adds in support for list the Custom Resource Definitions and it's overview page

Feat: Custom Resource Definition

---

.goreleaser.yaml
README.md

This PR adds build support for winget

build: add winget support

---

README.md
backend/config/config.go
backend/config/kube.go
backend/container/container.go
backend/routes/middleware/ClusterCacheMiddleware.go
backend/routes/routes.go
client/src/components/app/Sidebar/index.tsx

This PR fix:
* #51 
* Side-bar padding tweak

fix: liveliness probe failing and sidebar padding tweak

---

.github/workflows/releaser.yml

This PR updates.
* Use ubuntu 22-04
* Use snap for snacraft install

build: use-ubuntu 22.04 and snacraft cli update

---

backend/handlers/app/config.go

This PR will clear the cache instance on reload.

fix: clear cache on reload

---

backend/config/config.go
backend/config/kube.go

This PR update the qps and burst value also tweak the variable name of function to make it more cleaner.

refactor: updating qps - burst values and param name tweak

---

backend/config/config.go
backend/config/kube.go

This PR refactor the qps, burst and dir check

refactor: qps, burst and dir check 

---

.github/workflows/releaser.yml

This PR should fix the auto release and signing of helm charts.

ci: add helm chart

---

.goreleaser.yaml

This PR fix homebrew test command.

fix: homebrew test fix.

---

backend/handlers/crds/crds/definitions.go
backend/handlers/crds/resources/resources.go
backend/routes/routes.go

This PR update the code style for RouteHandler and Handlers for CRDs.

refactor: code style update for CRDs

---

backend/handlers/apply/apply.go

This PR will update the http header error code from 500 to 400 when failed to apply YAML.

fix: status code file for manifest apply errors

---

client/src/components/app/Details/Overview/index.tsx
client/src/components/app/MiscDetailsContainer/ClusterRoleBindingDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/ClusterRoleDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/ConfigMapDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/CustomResourceDetailsConainter.tsx
client/src/components/app/MiscDetailsContainer/Deployments/DeploymentDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/EndpointDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/LimitRangeDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/NamespaceDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/NodeDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/PodDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/PodDisruptionBudgetDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/ResourceQuotaDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/RoleBindingDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/RoleDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/RuntimeClassDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/ServiceAccountDetailsContainer.tsx
client/src/components/app/MiscDetailsContainer/ServiceDetailsContainer.tsx

This PR is updating card gap from mt-4 to mt-2 to make things in UI consitent.

fix: updating gap from mt-4 to mt-2
